# Generated by Django 5.0.6 on 2024-05-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guests',
            new_name='max_guests',
        ),
        migrations.AddField(
            model_name='room',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
