# Generated by Django 5.0.6 on 2024-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_guests_room_max_guests_room_avaliable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_out',
        ),
        migrations.AddField(
            model_name='room',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
