# Generated by Django 5.0.6 on 2024-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_remove_room_check_out_room_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='days',
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
