# Generated by Django 5.0.6 on 2024-06-04 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("principal", "0004_remove_room_days_room_check_out"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name="room",
            name="check_in",
        ),
        migrations.RemoveField(
            model_name="room",
            name="check_out",
        ),
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
        migrations.RemoveField(
            model_name="room",
            name="max_guests",
        ),
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
        migrations.AddField(
            model_name="room",
            name="num_room",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="room",
            name="type_room",
            field=models.CharField(
                choices=[
                    ("double", "Double"),
                    ("king", "King"),
                    ("two_double", "Two Double"),
                    ("suite", "Suite"),
                ],
                default=0,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("guests", models.PositiveIntegerField(default=2)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="principal.customer",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="principal.room"
                    ),
                ),
            ],
        ),
    ]
